App:
  name: learndocker
  virtual_host: localhost:8000
  cdn_host: http://localhost:8000
  use_ssl: false

Mongo:
  host: localhost
  port: 27017
  database: learndocker

Redis:
  host: localhost
  port: 6379